In [ ]:
#Name : Lakshya Sonawane
#PRN : 25070123068
#Title:Data Wrangling

In [ ]:
import pandas as pd
import numpy as np
df1 = pd.DataFrame({'C1':[11,21,np.nan],'C2':[15,np.nan,np.nan], 'C3':[10,20,30]})

df1

     C1    C2  C3
0  11.0  15.0  10
1  21.0   NaN  20
2   NaN   NaN  30

In [ ]:
df1.isna () #Boolean function

      C1     C2     C3
0  False  False  False
1  False   True  False
2   True   True  False

In [ ]:
df1.isna().sum() #columnwise na values

C1    1
C2    2
C3    0
dtype: int64

In [ ]:
df1.isna().sum(axis=1) #rowwise na values

0    0
1    1
2    2
dtype: int64

In [ ]:
df1.dropna() #NaN Rows are dropped

     C1    C2  C3
0  11.0  15.0  10

In [ ]:
df1.fillna(0) #fills nan values with given values

     C1    C2  C3
0  11.0  15.0  10
1  21.0   0.0  20
2   0.0   0.0  30

In [ ]:
df1.fillna(df1.mean(axis = 1)) #fills nan values with mean

     C1    C2  C3
0  11.0  15.0  10
1  21.0   NaN  20
2   NaN   NaN  30

In [ ]:
#Preprocessing on a Dataset - 1
import pandas as pd

data = {
    "Roll No": [101, 102, 103, 104, 105],
    "Name": ["Asha", "Rohan", "Meera", "Karan", "Anil"],
    "Age": [20, "-", 21, 20, "22"],
    "Marks": [85, 90, "-", 88, 76],
    "Department": ["CSE", "IT", "CSE", "cse", "E&TC"],
    "Admission_Date": ["01-06-2023", "03-06-2023", "05-06-2023", "07-06-2023", "10/06/23"]
}

df = pd.DataFrame(data)
print(df)

   Roll No   Name Age Marks Department Admission_Date
0      101   Asha  20    85        CSE     01-06-2023
1      102  Rohan   -    90         IT     03-06-2023
2      103  Meera  21     -        CSE     05-06-2023
3      104  Karan  20    88        cse     07-06-2023
4      105   Anil  22    76       E&TC       10/06/23

In [ ]:
#Step 2:Replace '-' with NaN to missing values

df.replace("-", np.nan, inplace=True)
df
#Convert columns to numeric where needed

   Roll No   Name  Age  Marks Department Admission_Date
0      101   Asha   20   85.0        CSE     01-06-2023
1      102  Rohan  NaN   90.0         IT     03-06-2023
2      103  Meera   21    NaN        CSE     05-06-2023
3      104  Karan   20   88.0        cse     07-06-2023
4      105   Anil   22   76.0       E&TC       10/06/23

In [ ]:
#Step 3:Check missing values

print("Missing Values:")
print(df.isna().sum())

Missing Values:
Roll No           0
Name              0
Age               1
Marks             1
Department        0
Admission_Date    0
dtype: int64

In [ ]:
#Step 4:
print("\nmissing values")
print(df.isna().sum())

missing values
Roll No           0
Name              0
Age               1
Marks             1
Department        0
Admission_Date    0
dtype: int64

In [ ]:
#Fill missing Age with mean
df["Age"].fillna(df["Age"].mean(), inplace=True)
df["Marks"].fillna(df["Marks"].median(), inplace=True)
df

TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [ ]:
#Step 5:
df["Department"] = df["Department"].str.upper()
df

   Roll No   Name  Age  Marks Department Admission_Date
0      101   Asha   20   85.0        CSE     01-06-2023
1      102  Rohan  NaN   90.0         IT     03-06-2023
2      103  Meera   21    NaN        CSE     05-06-2023
3      104  Karan   20   88.0        CSE     07-06-2023
4      105   Anil   22   76.0       E&TC       10/06/23

In [ ]:
# Step 6 : Convert Admission_Date to standard datetime format
df["Admission_Date"] = pd.to_datetime(df["Admission_Date"], errors='coerce')
df

   Roll No   Name  Age  Marks Department Admission_Date
0      101   Asha   20   85.0        CSE     2023-01-06
1      102  Rohan  NaN   90.0         IT     2023-03-06
2      103  Meera   21    NaN        CSE     2023-05-06
3      104  Karan   20   88.0        CSE     2023-07-06
4      105   Anil   22   76.0       E&TC            NaT